const itemsEl=document.querySelector('#cart-items');
const totalEl=document.querySelector('#cart-total');
const summaryTotal=document.querySelector('#summary-total');
const countEl=document.querySelector('#cart-item-count');
const toast=document.querySelector('#cart-toast');
const money=n=>`₱${n.toLocaleString('en-PH')}`;
const images={
'Forge Performance Tee':'https://images.unsplash.com/photo-1583743814966-8936f37f4a2b?auto=format&fit=crop&w=700&q=85','Forge Training Shorts':'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=700&q=85','Heavy Resistance Bands':'https://images.unsplash.com/photo-1598289431512-b97b0917affc?auto=format&fit=crop&w=700&q=85','Adjustable Hand Gripper':'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=700&q=85','Forge Shaker Bottle':'https://images.unsplash.com/photo-1594737625785-a6cbdabd333c?auto=format&fit=crop&w=700&q=85','Performance Gym Bag':'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=700&q=85','Wrist Wraps':'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=700&q=85','Forge Oversized Hoodie':'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=700&q=85'};
const get=()=>JSON.parse(localStorage.getItem('forge-cart')||'[]');
function save(c){localStorage.setItem('forge-cart',JSON.stringify(c));render()}
function notify(message){toast.textContent=message;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),1600)}
function render(){const cart=get(),count=cart.reduce((s,p)=>s+p.qty,0),total=cart.reduce((s,p)=>s+p.price*p.qty,0);countEl.textContent=`${count} ${count===1?'ITEM':'ITEMS'}`;totalEl.textContent=money(total);summaryTotal.textContent=money(total);
itemsEl.innerHTML=cart.length?cart.map((p,i)=>`<article class="cart-item" style="--delay:${i*70}ms"><div class="cart-product"><div class="cart-image" style="background-image:url('${images[p.name]||''}')"><span>${p.tag||'FORGE'}</span></div><div class="cart-product-copy"><small>${p.category}</small><h2>${p.name}</h2><p>${money(p.price)} each</p></div></div><div class="qty-control"><button aria-label="Decrease quantity" data-action="minus" data-i="${i}">−</button><b>${p.qty}</b><button aria-label="Increase quantity" data-action="plus" data-i="${i}">+</button></div><div class="cart-line-total"><strong>${money(p.price*p.qty)}</strong><button class="remove" data-action="remove" data-i="${i}">Remove</button></div></article>`).join(''):`<div class="empty-cart"><div class="empty-mark">∅</div><h2>Your bag is waiting.</h2><p>Nothing here yet. Find something worth training for.</p><a class="button button-primary" href="index.html#shop">Start Shopping <span>→</span></a></div>`}
itemsEl.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const i=+b.dataset.i,action=b.dataset.action,c=get(),name=c[i]?.name;if(action==='plus')c[i].qty++;if(action==='minus'){c[i].qty--;if(c[i].qty<=0){c.splice(i,1);notify(`${name} removed`)}}if(action==='remove'){c.splice(i,1);notify(`${name} removed`)}save(c)});
render();
